# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=75, null=True)),
                ('street', models.CharField(blank=True, max_length=75, null=True)),
                ('building', models.CharField(blank=True, max_length=75, null=True)),
                ('region', models.CharField(blank=True, max_length=75, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('footage', models.IntegerField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('planning', models.CharField(blank=True, max_length=75, null=True)),
                ('walltype', models.CharField(blank=True, max_length=75, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=75)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rentsite/')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
