# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='floors',
            new_name='floor_number',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='footage',
            new_name='living_footage',
        ),
        migrations.AddField(
            model_name='place',
            name='total_footage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
