# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_site', '0002_auto_20160326_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='walltype',
            new_name='wall_type',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
