# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_site', '0004_auto_20160326_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
