# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_site', '0005_auto_20160328_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='building',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='\u0414\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='place',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u042d\u0442\u0430\u0436'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rentsite/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0428\u0438\u0440\u043e\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='place',
            name='living_footage',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0416\u0438\u043b\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0414\u043e\u043b\u0433\u043e\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='place',
            name='planning',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='\u041f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u043e\u043c\u043d\u0430\u0442'),
        ),
        migrations.AlterField(
            model_name='place',
            name='street',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='\u0423\u043b\u0438\u0446\u0430'),
        ),
        migrations.AlterField(
            model_name='place',
            name='total_footage',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041e\u0431\u0449\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c'),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(max_length=75, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='place',
            name='wall_type',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0435\u043d'),
        ),
    ]
