# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_site', '0006_auto_20160328_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
